### ISSUE TITLE
`providence replay` and `providence save` raise an exception

### ISSUE THREAD

**Issue by Equinoz** [guillaumeLamanda/providence-server#26]
When I run the `providence replay` command without specific folder or the `providence save` command, I get the error below:
```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at join (path.js:1148:7)
    at getReplayFolder (file:///home/julien/.npm-global/lib/node_modules/providence-server/src/server.js:31:12)
    at start (file:///home/julien/.npm-global/lib/node_modules/providence-server/src/server.js:33:28)
    at Command.<anonymous> (file:///home/julien/.npm-global/lib/node_modules/providence-server/src/cli.js:59:5)
    at Command.listener [as _actionHandler] (/home/julien/.npm-global/lib/node_modules/providence-server/node_modules/commander/lib/command.js:488:17)
    at /home/julien/.npm-global/lib/node_modules/providence-server/node_modules/commander/lib/command.js:1207:65
    at Command._chainOrCall (/home/julien/.npm-global/lib/node_modules/providence-server/node_modules/commander/lib/command.js:1124:12)
    at Command._parseCommand (/home/julien/.npm-global/lib/node_modules/providence-server/node_modules/commander/lib/command.js:1207:27)
    at Command._dispatchSubcommand (/home/julien/.npm-global/lib/node_modules/providence-server/node_modules/commander/lib/command.js:1031:25) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
Nevertheless, data is present in `~/.npm-global/lib/node_modules/providence-server/data/current/` folder

**Comment by guillaumeLamanda** [comment]
Hi @Equinoz! 

Thanks for reporting.  
I've tried to reproduce, but it works as expected on my side.  
I've used the followings commands: 

```bash
npx providence-server proxy -h animechan.vercel.app
# in another terminal 
curl http://localhost:3000/api/random 
# kill the proxy, then
npx providence-server replay 
curl http://localhost:3000/api/random # => work as expected
```

Could you give me the commands to reproduce?
